version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/python_project

hooks:
  BeforeInstall:
    - location: scripts/clean_instance.sh
      runas: root
  AfterInstall:
    - location: scripts/install_python_dependencies.sh
      timeout: 6000
      runas: ec2-user
  ApplicationStart:
    - location: scripts/start_application.sh
      timeout: 6000
      runas: ec2-user
  

